config/routes.rb
Proctoring::Engine.routes.draw do
  resources :video_streamings do
    collection do
      get 'distribute_channel_to_rooms'
      get 'user_channel'
    end
    member do
      get 'event'
      get 'stream_channel'
      get 'stream_room'
      post 'upload_video'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :authentication, only: :create

      namespace :hundred_ms do
        resources :services, only: :create
      end
    end
  end
end

app/models/proctoring/application_record.rb
module Proctoring
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/proctoring/video_streaming.rb
module Proctoring
  class VideoStreaming < ApplicationRecord
    validates :channel,  presence: true
    validates :user_id,  presence: true
    validates :event_id, presence: true
    validates_uniqueness_of :user_id, scope: [:event_id]
    has_many_attached :images
    has_many_attached :videos

    enum status: { active: 0, stopped: 1 }

    before_validation :ensure_channel_has_a_value

    scope :by_event, ->(event_id) { where(event_id: event_id) }
    
    def all_attached_videos_sign_ids
      videos.map(&:signed_id)
    end

    def self.setup_rooms(event_id, no_of_users_in_channel)
      @channels = VideoStreaming.by_event(event_id).active.pluck(:channel)
      video_streaming_room = VideoStreamingRoom.where(event_id: event_id, total_users: no_of_users_in_channel).active
      if (video_streaming_room.length.positive?)
        channels_in_room = video_streaming_room.pluck(:channels)&.flatten
        return if @channels == channels_in_room
        video_streaming_room.map(&:closed!)
      end

      channels_by_room = @channels.each_slice(no_of_users_in_channel).to_a if @channels.length.positive? && no_of_users_in_channel.positive?
      VideoStreaming.transaction do
        channels_by_room.each do |channels|
          VideoStreamingRoom.create(event_id: event_id, total_users: no_of_users_in_channel, channels: channels)
        end
      end
    end

    def self.open_join_channel(user_id, event_id)
      video_streaming = VideoStreaming.find_by(event_id: event_id, user_id: user_id)
      unless video_streaming
        video_streaming = VideoStreaming.create(event_id: event_id, user_id: user_id)
      end
      video_streaming
    end

    private

      def ensure_channel_has_a_value
        if channel.nil?
          self.channel = SecureRandom.uuid
          self.status = :active
        end
      end
  end
end

app/models/proctoring/video_streaming_room.rb
module Proctoring
  class VideoStreamingRoom < ApplicationRecord
    validates :room,  presence: true
    validates :event_id, presence: true
    validates :channels, presence: true
    validates :total_users, presence: true

    # validate :check_total_users_equals_channels

    enum status: { active: 0, closed: 1 }

    before_validation :ensure_room_has_a_value

    private

      def ensure_room_has_a_value
        if room.nil?
          self.room = SecureRandom.uuid
          self.status = :active
        end
      end

      # def check_total_users_equals_channels
      #   if self.total_users != self.channels&.length
      #     errors.add(:total_users, "Total users are not equal to channels in room.")
      #   end
      # end
  end
end

app/controllers/proctoring/api/v1/authentication_controller.rb
# frozen_string_literal: true

module Proctoring::Api::V1
  class AuthenticationController < Proctoring::ApplicationController
    include Proctoring::TokensHelper
    include Proctoring::HundredMsServiceHelper
    before_action :authenticate_app_token

    def create
      event_id = params[:event_id]
      user_id = params[:user_id]
      role = params[:role]
      max_people_allowed = params[:max_people_allowed]

      room_id = room_already_exists?(event_id, user_id)

      room_id ||= room_exists_with_space?(event_id, user_id, role, max_people_allowed)

      if room_id.blank?
        room_id = generate_room({ event_id: event_id })['id']
        add_room_to_the_cache(room_id, user_id, role, event_id)
      end

      authentication_params = { user_id: user_id, role: role, room_id: room_id }
      authentication_token = generate_authentication_token(authentication_params)
      render json: { success: true, authentication_token: authentication_token }
    rescue StandardError => e
      render json: { success: false, error: e.message }, status: :internal_server_error
    end
  end
end

app/controllers/proctoring/api/v1/hundred_ms/services_controller.rb
# frozen_string_literal: true

module Proctoring::Api::V1
  module HundredMs
    class ServicesController < Proctoring::ApplicationController
      skip_before_action :verify_authenticity_token
      before_action :authenticate_api_token

      def create
        hundred_ms_response = JSON.parse(request.raw_post)

        case hundred_ms_response['type']
        when 'recording.success'
          data = hundred_ms_response['data']
          room_name = data['room_name']
          invitation_code = room_name.split('-').first
          ProctoringStorageHelper.initiate_processing(invitation_code)
        end

        render json: { success: true }
      end
    end
  end
end

app/controllers/proctoring/application_controller.rb
module Proctoring
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def authenticate_app_token
      token_valid? request.headers['Token']
    end

    def authenticate_api_token
      return if request.headers['Api-Secret'] == Proctoring.hundred_ms_webhook_secret

      render json: { success: false, error: 'You are not an authorized person.' }, status: :unauthorized
    end

    private

    def token_valid?(token)
      JWT.decode token, Proctoring.hundred_ms_auth_secret, true, { algorithm: 'HS256' }
    rescue StandardError => _e
      render json: { success: false, error: 'You are not an authorized person.' }, status: :unauthorized
    end
  end
end

app/controllers/proctoring/video_streamings_controller.rb
require_dependency "proctoring/application_controller"

module Proctoring
  class VideoStreamingsController < ApplicationController
    before_action :set_video_streaming, only: [:show, :edit, :update, :destroy, :upload_video]

    # GET /video_streamings
    def index
      @video_streamings = VideoStreaming.where(status: :active).limit(15)
    end

    # GET /video_streamings/1
    def show
    end

    # GET /video_streamings/new
    def new
      @video_streaming = VideoStreaming.new
    end

    # GET /video_streamings/1/edit
    def edit
    end

    # POST /video_streamings
    def create
      @video_streaming = VideoStreaming.new(video_streaming_params)

      if @video_streaming.save
        redirect_to @video_streaming, notice: 'Video streaming was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /video_streamings/1
    def update
      if @video_streaming.update(video_streaming_params)
        redirect_to @video_streaming, notice: 'Video streaming was successfully updated.'
      else
        render :edit
      end
    end

    # PATCH/PUT /video_streamings/1/upload_video
    def upload_video
      video_streaming = video_streaming_params
      # return unless session[:user_id] != video_streaming[:user_id]
      # video_streaming[:videos] = @video_streaming.all_attached_videos_sign_ids + video_streaming[:videos]
      # p video_streaming
      if @video_streaming.update(video_streaming_params)
        render json: {}, status: :ok
      else
        render json: {}, status: 422
      end
    end

    # DELETE /video_streamings/1
    def destroy
      @video_streaming.stopped!
      redirect_to video_streamings_url, notice: 'Video streaming was successfully destroyed.'
    end

    def event
      @video_streamings = VideoStreaming.by_event(params[:id])
    end

    def user_channel
      user_id = params[:user_id]
      event_id = params[:event_id]
      video_streaming = VideoStreaming.open_join_channel(user_id, event_id)
      render json: { id: video_streaming.id, channel: video_streaming.channel, socketURL: Proctoring.media_server_url }
    end

    def stream_channel
      @media_server_url = Proctoring.media_server_url
      @video_streaming = VideoStreaming.find_by(channel: params[:id])
      @channels = [@video_streaming.channel]
    end

    def stream_room
      @media_server_url = Proctoring.media_server_url
      @video_streaming_room = VideoStreamingRoom.find_by(room: params[:id])
    end

    def distribute_channel_to_rooms
      @no_of_users_in_channel = proctor_user_params[:no_of_users_in_channel].to_i
      @event_id = proctor_user_params[:event_id]
      VideoStreaming.setup_rooms(@event_id, @no_of_users_in_channel)
      @all_rooms = VideoStreamingRoom.where(event_id: @event_id, total_users: @no_of_users_in_channel).active
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_video_streaming
        @video_streaming = VideoStreaming.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def video_streaming_params
        params.require(:video_streaming).permit(:channel, :user_id, :event_id, videos: [], images: [])
      end

      def proctor_user_params
        params.require(:video_streaming).permit(:no_of_users_in_channel, :event_id)
      end
  end
end

app/helpers/proctoring/application_helper.rb
module Proctoring
  module ApplicationHelper
  end
end

app/helpers/proctoring/hundred_ms_service_helper.rb
# frozen_string_literal: true

require 'net/http'
module Proctoring
  module HundredMsServiceHelper
    include Proctoring::TokensHelper
    def generate_room(params)
      uri = get_api_url('create_room')
      uri = URI.parse(uri)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      request = Net::HTTP::Post.new(uri.path, { 'Content-Type' => 'application/json' })
      request['Authorization'] = "Bearer #{generate_management_token}"
      body = get_create_room_request_parameters(params[:event_id])
      request.body = body.to_json
      response = http.request(request)
      JSON.parse(response.body)
    end

    def room_already_exists?(event_id, user_id)
      rooms = fetch_rooms_for_a_event(event_id)
      return if rooms.blank?

      rooms.each do |room_id, candidates|
        candidates.each do |candidate_hash|
          return room_id if candidate_hash[:user_id] == user_id
        end
      end; nil
    end

    def room_exists_with_space?(event_id, user_id, role, max_people_allowed)
      rooms = fetch_rooms_for_a_event(event_id)
      return if rooms.blank?

      rooms.each do |room_id, candidates|
        roles = candidates.map { |candidate_hash| candidate_hash[:role] }
        next if roles.count(role) >= max_people_allowed.to_i

        candidates << { user_id: user_id, role: role }
        rooms[room_id] = candidates
        Rails.cache.write("100ms_room_details_#{event_id}", rooms, expires_in: 2.hours)
        return room_id
      end; nil
    end

    def add_room_to_the_cache(room_id, user_id, role, event_id)
      candidates = [{ user_id: user_id, role: role }]
      rooms = fetch_rooms_for_a_event(event_id) || {}
      rooms[room_id] = candidates
      Rails.cache.write("100ms_room_details_#{event_id}", rooms, expires_in: 2.hours)
    end

    private

    def get_api_url(service_name)
      case service_name
      when 'create_room'
        'https://api.100ms.live/v2/rooms'
      end
    end

    def get_create_room_request_parameters(event_id)
      {
        name: "#{event_id}-#{SecureRandom.uuid}",
        description: "Room for the event with id - #{event_id}",
        template_id: Proctoring.hundred_ms_template_id,
        recording_info: {
          enabled: true,
          upload_info: {
            type: 's3',
            location: Proctoring.hundred_ms_s3_bucket,
            prefix: event_id,
            options: {
              region: Proctoring.hundred_ms_s3_region
            },
            credentials: {
              key: Proctoring.hundred_ms_s3_access_key,
              secret: Proctoring.hundred_ms_s3_access_secret
            }
          }
        },
        region: 'in'
      }
    end

    def fetch_rooms_for_a_event(event_id)
      Rails.cache.read("100ms_room_details_#{event_id}")
    end
  end
end

app/helpers/proctoring/tokens_helper.rb
# frozen_string_literal: true
require 'jwt'
require 'securerandom'

module Proctoring
  module TokensHelper
    def generate_authentication_token(params)
      now = Time.now
      exp = now + 1.day
      payload = {
        access_key: Proctoring.hundred_ms_app_access_key,
        room_id: params[:room_id],
        user_id: params[:user_id],
        role: params[:role],
        type: 'app',
        jti: SecureRandom.uuid,
        version: 2,
        iat: now.to_i,
        nbf: now.to_i,
        exp: exp.to_i
      }
      JWT.encode(payload, Proctoring.hundred_ms_app_secret, 'HS256')
    end

    def generate_management_token
      now = Time.now
      exp = now + 1.day
      payload = {
        access_key: Proctoring.hundred_ms_app_access_key,
        type: 'management',
        version: 2,
        jti: SecureRandom.uuid,
        iat: now.to_i,
        nbf: now.to_i,
        exp: exp.to_i
      }
      JWT.encode(payload, Proctoring.hundred_ms_app_secret, 'HS256')
    end

    def self.encode_authentication_token
      now = Time.now
      exp = now + 10.minutes
      payload = {
        app_name: Proctoring.app_name,
        type: 'application',
        jti: SecureRandom.uuid,
        version: 2,
        iat: now.to_i,
        nbf: now.to_i,
        exp: exp.to_i
      }
      JWT.encode payload, Proctoring.hundred_ms_auth_secret, 'HS256'
    end
  end
end

app/helpers/proctoring/video_streamings_helper.rb
module Proctoring
  module VideoStreamingsHelper
  end
end

app/views/proctoring/video_streamings/_form.html.erb
<%= form_with(model: video_streaming, local: true) do |form| %>
  <% if video_streaming.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video_streaming.errors.count, "error") %> prohibited this video_streaming from being saved:</h2>

      <ul>
        <% video_streaming.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proctoring/video_streamings/_record_video_from_client.html.erb
<%= content_tag :div, '', id: "video-recording-info", data: {
  app_name: Proctoring.app_name,
  record_endpoint: '/proctoring/video_streamings',
  upload_url: rails_direct_uploads_url,

} %>
<%= javascript_include_tag "activestorage" %>
<%= javascript_include_tag "proctoring/video_recorder" %>

app/views/proctoring/video_streamings/_socket_rtc_scripts.html.erb
<script src="https://cdn.jsdelivr.net/npm/rtcmulticonnection@3.7.0/dist/RTCMultiConnection.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"></script>
<% if defined? recording %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/RecordRTC/5.6.1/RecordRTC.min.js"></script>
<%end%>

app/views/proctoring/video_streamings/_stream_video.html.erb
<%= render partial: 'socket_rtc_scripts', locals: { recording: true } %>
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Video Streamings</h1>
  <div id="channel-data" data-stream-video-url="<%= media_server_url %>" data-stream-channels="<%= channels %>"></div>
  <div id="video-container"></div>
</div>
<%= javascript_include_tag "proctoring/stream_room" %>

app/views/proctoring/video_streamings/_video_recording.html.erb
<%= javascript_include_tag 'kurento/kurento-utils' %>
<%= javascript_include_tag 'kurento/VideoRecordingUsingSignalingServer' %>
<%= content_tag :div, '', id: 'proctoring-data', data: { media_server_url: Proctoring.media_server_url, app_name: Proctoring.app_name } %>

app/views/proctoring/video_streamings/_video_recording100ms.html.erb
<%= javascript_include_tag '100ms/examine', type: 'module' %>
<%= content_tag :div, '', id: 'proctoring-data', data: {} %>
<%= content_tag :div, '', id: 'application-token', data: { token: Proctoring::TokensHelper::encode_authentication_token } %>

app/views/proctoring/video_streamings/distribute_channel_to_rooms.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>
<h1>Video Streamings</h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th>Total Rooms</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @all_rooms.length%></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="panel panel-default" style="margin-top: 15px;">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Channel Id</th>
        <th>View Live</th>
      </tr>
    </thead>
    <tbody>
      <% @all_rooms.each do |room| %>
        <tr>
          <td> <%= room.room %></td>
          <td> <%= link_to 'Live', stream_room_video_streaming_path(id: room.room) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/proctoring/video_streamings/edit.html.erb
<h1>Editing Video Streaming</h1>

<%= render 'form', video_streaming: @video_streaming %>

<%= link_to 'Show', @video_streaming %> |
<%= link_to 'Back', video_streamings_path %>

app/views/proctoring/video_streamings/event.html.erb
<%= render partial: "list" %>

<div>
  <%= form_for :video_streaming, url: distribute_channel_to_rooms_video_streamings_path, method: :get do |f| %>
    <%= f.text_field :no_of_users_in_channel, placeholder: 'Enter the amount of candidate you want in a room.', size: '50' %>
    <%= f.hidden_field :event_id, { value: params[:id] } %>
    <%= f.submit "Distribute channels to rooms" %>
  <% end %>
</div>

app/views/proctoring/video_streamings/index.html.erb
<%= render partial: "list" %>

app/views/proctoring/video_streamings/new.html.erb
<h1>New Video Streaming</h1>

<%= render 'form', video_streaming: @video_streaming %>

<%= link_to 'Back', video_streamings_path %>

app/views/proctoring/video_streamings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @video_streaming.channel %>
</p>

<p>
  <strong>Event:</strong>
  <%= @video_streaming.event_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @video_streaming.user_id %>
</p>

<%= link_to 'Edit', edit_video_streaming_path(@video_streaming) %> |
<%= link_to 'Back', video_streamings_path %>

app/views/proctoring/video_streamings/stream_channel.html.erb
<%= render partial: "stream_video", locals: { media_server_url: @media_server_url, channels: [@video_streaming.channel]} %>

app/views/proctoring/video_streamings/stream_room.html.erb
<%= render partial: "stream_video", locals: { media_server_url: @media_server_url, channels: @video_streaming_room.channels} %>